language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_install:
    - travis_retry composer selfupdate

install:
    - travis_retry composer install --prefer-dist --dev

script:
    - vendor/bin/phpunit --verbose --coverage-text

matrix:
    fast_finish: true

    allow_failures:
        - php: 7.0
        - php: hhvm
